<?php function getContent(){ ?>
	<div class="row main">
		<div class="col-md-12 disclaimer">

			<h1>Disclaimer</h1>

			<p>Last updated: August 20, 2018</p>

			<p>The information contained on https://jeanne24.github.io/ecommerce/ website (the "Service") is for general information purposes only.</p>

			<p>ReBook assumes no responsibility for errors or omissions in the contents on the Service.</p>

			<p>In no event shall ReBook be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. ReBook reserves the right to make additions, deletions, or modification to the contents on the Service at any time without prior notice. This Disclaimer  for ReBook is <a href="https://termsfeed.com/disclaimer/generator/">generated by TermsFeed</a></p>

			<p>ReBook does not warrant that the website is free of viruses or other harmful components.</p>

			<h2>External links disclaimer</h2>

			<p>https://jeanne24.github.io/ecommerce/ website may contain links to external websites that are not provided or maintained by or in any way affiliated with ReBook</p>

			<p>Please note that the ReBook does not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.</p>
			
		</div>
	</div>
<?php };

function getTitle() {
	echo 'Rebook - Resell your old books, buy books for less.';
}
require_once "partials/template.php";
 ?>
